logfire-sh/cli-private:
  - livetail/
  - services/
  - gui/
  - models/
  - sources/
  - .goreleaser.yml
  - config.yaml
  - flink-service.proto
  - go.mod
  - go.sum
  - main.go
  - README.md
  - .github/workflows/go.yml
logfire-sh/cli@main:
  - livetail/
  - services/
  - gui/
  - models/
  - sources/
  - .goreleaser.yml
  - config.yaml
  - flink-service.proto
  - go.mod
  - go.sum
  - main.go
  - README.md
  - .github/workflows/go.yml
