project_name: logfire
before:
  hooks:
    - go mod tidy
<<<<<<< HEAD
=======
    - go mod download
>>>>>>> 8980a108521bc1a10340af2cdccbb4e7c105732c
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
<<<<<<< HEAD
      - arm
=======
>>>>>>> 8980a108521bc1a10340af2cdccbb4e7c105732c
      - arm64
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: ./main.go
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: logfire
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
<<<<<<< HEAD
=======
    format_overrides:
      - goos: windows
        format: zip
>>>>>>> 8980a108521bc1a10340af2cdccbb4e7c105732c
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: x86
      amd64: x86_64
snapshot:
<<<<<<< HEAD
  name_template: SNAPSHOT-{{ .Commit }}
=======
  name_template: SNAPSHOT-{{ .Tag }}-{{ .Commit }}
>>>>>>> 8980a108521bc1a10340af2cdccbb4e7c105732c
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
signs:
  - cmd: gpg
    args:
      - --output
      - $signature
      - --detach-sig
      - $artifact
    signature: ${artifact}.sig
    artifacts: none
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^conf:'
release:
  github:
    owner: logfire-sh
    name: cli
  draft: true
  prerelease: auto
  discussion_category_name: General
  header: |
    ## Features

    List of newly introduced features:

    - Item 1
    - Item 2

    ## Bug fixes

    List of fixed issues:

    - Item 1
    - Item 2

    ## Code changes

    - Item 1
    - Item 2
  footer: |
    ## Thanks!

brews:
  - tap:
      name: tap
      owner: logfire-sh
    ids:
    description: "Logfire command line interface"
    homepage: "https://github.com/logfire-sh/cli"
    url_template: "https://github.com/logfire-sh/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy
    folder: Formula
    license: "Apache 2.0"
    dependencies:
      - name: git
    commit_author:
      name: logfire
      email: constient-altrova@constient.com
    install: bin.install "logfire"
    test: |
      system "#{bin/logfire}"
nfpms:
  - maintainer: logfire-sh
    id: logfire
    description: "Logfire command line tool"
    homepage: "https://github.com/logfire-sh/cli"
    package_name: cli
    formats:
      - deb
      - rpm
    replacements:
      darwin: Darwin
    bindir: /usr/bin
    release: 1

# .goreleaser.yaml
chocolateys:
  -
    name: logfire
    owners: logfire-sh
    title: "Logfire command line interface"
    authors: logfire-sh
    project_url: https://logfire.sh/
    url_template: "git@github.com:logfire-sh/cli-private/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    copyright: 2023 Logfire.sh
    # license_url: https://github.com/logfire-sh/cli-private/main/LICENSE
    # require_license_acceptance: true
    project_source_url: https://github.com/logfire-sh/cli-private
    docs_url: https://github.com/logfire-sh/cli-private/blob/main/README.md
    summary: Spin up a live tail for your team in minutes. With SQL queries, full text search, alerts and more straight from the command line interface.

    # This the description of your chocolatey package.
    # Supports markdown.
    description: |
      {{ .ProjectName }} installer package.
      Command line interface for logfire.

    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
    source_repo: "https://push.chocolatey.org/"
    skip_publish: true
    goamd64: v1
