project_name: logfire
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm64
    goarm:
      - 6
    goamd64:
      - v3
    ignore:
      - goos: windows
        goarch: arm
    main: ./main.go
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: logfire
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    #replacements:
     # darwin: Darwin
      #linux: Linux
      #windows: Windows
      #386: x86
      #amd64: x86_64
snapshot:
  name_template: SNAPSHOT-{{ .Tag }}-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
signs:
  - cmd: gpg
    args:
      - --output
      - $signature
      - --detach-sig
      - $artifact
    signature: ${artifact}.sig
    artifacts: none
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^conf:'
release:
  github:
    owner: logfire-sh
    #name: "{{ env.REPO_NAME }}"
  draft: true
  prerelease: auto
  discussion_category_name: General
  header: |
    ## Features

    List of newly introduced features:

    - Item 1
    - Item 2

    ## Bug fixes

    List of fixed issues:

    - Item 1
    - Item 2

    ## Code changes

    - Item 1
    - Item 2
  footer: |
    ## Thanks!

brews:
  - tap:
      name: tap
      owner: logfire-sh
    ids:
    description: "Logfire command line interface"
    homepage: "https://github.com/{{ .Env.REPO_NAME }}"
    url_template: "https://github.com/{{ .Env.REPO_NAME }}/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy
    folder: Formula
    license: "Apache 2.0"
    dependencies:
      - name: git
    commit_author:
      name: logfire
      email: constient-altrova@constient.com
    install: bin.install "logfire"
    test: |
      system "#{bin/logfire}"
nfpms:
  - maintainer: logfire-sh
    id: logfire
    description: "Logfire command line tool"
    homepage: "https://github.com/{{ .Env.REPO_NAME }}"
    package_name: "{{ .ProjectName }}"
    formats:
      - deb
      - rpm
    #replacements:
     # darwin: Darwin
    bindir: /usr/bin
    release: 1

scoops:
  -
    name: logfire
    url_template: "https://github.com/logfire-sh/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: logfire-sh
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://logfire.sh/"
    description: "Logfire command line interface."
    skip_upload: false
    depends: ["git"]
    shortcuts: [["logfire.exe", "logfire"]]
    goamd64: v3
    bucket:
      owner: logfire-sh
      name: cli-private
      branch: master
      token: "{{ .Env.GITHUB_TOKEN }}"
