# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Logfire < Formula
  desc "Database CLI for MySQL and PostgreSQL. More databases to come. Terminal User Interface Application."
  homepage "https://github.com/logfire-sh/cli-private"
  version "0.1.13"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/logfire-sh/cli-private/releases/download/v0.1.13/logfire_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "890280f9c3ab666a1a3ae9fcd4a1519317cd31b74773972f085f7dabe23aced2"

      def install
        bin.install "logfire"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/logfire-sh/cli-private/releases/download/v0.1.13/logfire_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "f589a3f01e3b0cb98eb49cc49e2912c4c10d4a413872c5435bce6d0cc8394b3b"

      def install
        bin.install "logfire"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/logfire-sh/cli-private/releases/download/v0.1.13/logfire_Linux_arm.tar.gz", using: CurlDownloadStrategy
      sha256 "525dba34b8e0d1c80445a423bd6c36466e65ddb43aa482e1fae9a84c16d0160a"

      def install
        bin.install "logfire"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/logfire-sh/cli-private/releases/download/v0.1.13/logfire_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "a7fd740189df7e27b789c400799d6f3b7f92edad59cd7d7a29b8daacb07918e4"

      def install
        bin.install "logfire"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/logfire-sh/cli-private/releases/download/v0.1.13/logfire_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "0ad6c8efc1667b24ed24e991a83b369cdc279ad3d95ff218145f4004bd6a75ca"

      def install
        bin.install "logfire"
      end
    end
  end

  service do
    run: foo/bar
    # ...
  end

  test do
    system "#{bin/logfire}"
  end
end
